<?php
/*
 * @copyright   Copyright (C) 2010-2024 TeemIp
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'teemip-bridge-virtualization-network-extended/3.0.1',
	array(
		// Identification
		//
		'label' => 'Links between virtualization and network extended',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'teemip-virtualization-mgmt-adaptor/3.0.1',
			'teemip-network-mgmt-extended/3.0.1',
		),
		'mandatory' => false,
		'visible' => false,
		'auto_select' => 'SetupInfo::ModuleIsSelected("teemip-virtualization-mgmt-adaptor") && SetupInfo::ModuleIsSelected("teemip-network-mgmt-extended")',

		// Components
		//
		'datamodel' => array(
			'model.teemip-bridge-virtualization-network-extended.php', // Contains the PHP code generated by the "compilation" of datamodel.teemip-cable-mgmt.xml
		),
		'data.struct' => array(
			//'data.struct.itop-change-mgmt.xml',
		),
		'data.sample' => array(
			//'data.sample.itop-change-mgmt.xml',
		),

		// Documentation
		//
		'doc.manual_setup' => '',
		'doc.more_information' => '',

		// Default settings
		//
		'settings' => array(
		),
	)
);
